# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [19]:
import numpy as np


#### 2. Print the numpy version and the configuration 

In [20]:
print(np.__version__)


1.19.5


#### 3. Create a null vector of size 10

In [21]:
x = np.zeros(10)


#### 4.  How to find the memory size of any array

In [22]:
print(x.itemsize)
print(len(x))

8
10


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [23]:
?np.add

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [24]:
x = np.zeros(10)
x[4]=1

#### 7.  Create a vector with values ranging from 10 to 49

In [25]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [26]:
res = v[::-1]
print(res)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [28]:
x=np.array( [1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [29]:
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [30]:
x = np.random.random((3,3,3))
print(x)

[[[0.90980182 0.0637839  0.69166913]
  [0.15299325 0.70025179 0.27333706]
  [0.88342    0.33123401 0.85197161]]

 [[0.17710265 0.24147534 0.64356624]
  [0.80989375 0.89842685 0.50015509]
  [0.88012367 0.71373298 0.00224823]]

 [[0.71365062 0.23249475 0.73480073]
  [0.42806856 0.36392078 0.12516535]
  [0.22565948 0.38086847 0.79099278]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [31]:

x = np.random.random((10,10))
xmin  = x.min() 
xmax = x.max()
print(xmin)
print(xmax)

0.004979666847170217
0.9975220383363844


#### 14. Create a random vector of size 30 and find the mean value

In [32]:
x = np.random.random(30)
print(x)

[0.55269142 0.18143672 0.96585805 0.34713489 0.00130919 0.25283546
 0.37411254 0.09596947 0.59337325 0.46900596 0.37288059 0.98850832
 0.04761801 0.73286507 0.75566805 0.80110718 0.19852363 0.81895511
 0.03939704 0.41810738 0.53078863 0.43228927 0.33868337 0.34008867
 0.46825181 0.71433292 0.47360122 0.5640837  0.93705798 0.04289952]


#### 15. Create a 2d array with 1 on the border and 0 inside

In [33]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [34]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [36]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [37]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)
